# fly.toml app configuration file generated for oink-back on 2023-04-22T13:48:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "oink-back"
primary_region = "mia"

[env]
  PORT = "8000"         # new

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[deploy]
  release_command = "python manage.py migrate --noinput"