# Generated by Django 4.1.7 on 2023-04-07 22:07

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ('nome', models.CharField(max_length=255, default='')),
                ('thumb', models.CharField(default='', null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('ispb', models.CharField(max_length=10, default='')),
            ],
        )
    ]
