# Generated by Django 4.2 on 2023-05-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicoes',
            name='thumb',
            field=models.CharField(blank=True, default=''),
        ),
    ]
