# Generated by Django 4.2 on 2023-06-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instituicoes", "0002_alter_instituicoes_thumb"),
    ]

    operations = [
        migrations.AddField(
            model_name="instituicoes",
            name="image_link",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
