# Generated by Django 4.1.7 on 2023-04-06 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
