# Generated by Django 4.1.7 on 2023-04-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
