# Generated by Django 4.2 on 2023-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instituicoes", "0001_initial"),
        ("usuarios", "0002_usuario_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="instituicoes",
            field=models.ManyToManyField(to="instituicoes.instituicoes"),
        ),
    ]
