# Generated by Django 4.1.7 on 2023-04-12 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_email_verified',
        ),
    ]
