# Generated by Django 4.1.7 on 2023-04-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_usuario_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_email_virified',
            field=models.BooleanField(default=False),
        ),
    ]
