# Generated by Django 4.1.7 on 2023-04-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_is_email_virified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_email_virified',
            new_name='is_email_verified',
        ),
    ]
