# Generated by Django 4.1.7 on 2023-04-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_is_email_virified_usuario_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token_confirmacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
