# Generated by Django 4.1.7 on 2023-04-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='token_confirmacao',
        ),
    ]
