# Generated by Django 4.2 on 2023-05-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_instituicoes'),
        ('usuarios', '0010_alter_usuario_email'),
    ]

    operations = [
    ]
