# Generated by Django 4.2 on 2023-06-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0002_investimentos_logo'),
        ('usuarios', '0013_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='investimentos',
            field=models.ManyToManyField(to='investimentos.investimentos'),
        ),
    ]
