# Generated by Django 4.2 on 2023-06-18 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investimentos', '0002_investimentos_logo'),
        ('usuarios', '0014_usuario_investimentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeusInvestimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=100)),
                ('investimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investimentos.investimentos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
