# Generated by Django 4.2 on 2023-06-18 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_meusinvestimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='meusinvestimentos',
            name='data_movimentacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
