# Generated by Django 4.2.2 on 2023-06-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_minhascryptos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeusInvestimentos',
        ),
    ]
