# Generated by Django 4.2.2 on 2023-06-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_delete_meusinvestimentos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minhascryptos',
            old_name='cryto',
            new_name='crypto',
        ),
    ]
