# Generated by Django 4.1.7 on 2023-04-08 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
