# Generated by Django 4.2 on 2023-04-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("instituicoes", "0001_initial"),
        ("movimentacoes", "0002_alter_movimentacoes_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacoes",
            name="instituicao",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="instituicoes.instituicoes",
            ),
            preserve_default=False,
        ),
    ]
