# Generated by Django 4.2 on 2023-04-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contas", "0001_initial"),
        ("movimentacoes", "0003_movimentacoes_instituicao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movimentacoes",
            name="instituicao",
        ),
        migrations.AddField(
            model_name="movimentacoes",
            name="conta",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contas.contas",
            ),
            preserve_default=False,
        ),
    ]
