# Generated by Django 4.2 on 2023-05-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_remove_movimentacoes_instituicao_movimentacoes_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacoes',
            name='conta',
        ),
    ]
