# Generated by Django 4.2 on 2023-05-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0007_movimentacoes_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='categoria',
            field=models.CharField(choices=[('OUTROS', 'Outros'), ('COMIDA', 'Comida'), ('ALUGUEL', 'Aluguel'), ('CONTAS', 'Contas'), ('ESTUDOS', 'Estudos'), ('ROUPAS', 'Roupas'), ('CASA', 'Casa'), ('MEDICO', 'Médico'), ('ENTRETENIMENTO', 'Entretenimento'), ('SALARIO', 'Salário'), ('TRABALHO', 'Trabalho'), ('TRANSPORTE', 'Transporte'), ('CLIENTE', 'Cliente'), ('VIAGEM', 'Viagem')], default='OUTROS'),
        ),
    ]
